config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    get 'drafts', on: :collection
    get 'search', on: :collection
  end 

resources :users
get '/signup', to: 'users#new'

root :to => 'welcome#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
    scope :most_recent, -> { limit(10).order('published_at desc') }
    scope :unpublished, -> { where("published_at > '#{Date.today}'")}
    
    def self.search(q)
      where(['body LIKE ? OR subject LIKE ?', "%#{q}%", "%#{q}%"])
    end 
end

app/models/user.rb
class User < ActiveRecord::Base
  #Add save handlers for formatting data
  before_create :create_remember_token
  before_save :normalize_fields
  # Validates name:
  validates :name,
    presence: true,
    length: {maximum: 50}

  # Validates email:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false},
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  #or use:   /[^@]+@[^@]+/

  # Validates password length
  validates :password,
    length: { minimum: 8 }

  # secure passwrd features
  has_secure_password


  # create a new remember token for the user:
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  # creates a new session token for the user
  def create_remember_token
    remember_token = User.hash(User.new_remember_token)
  end
  #  normalize fields for consistancy
  def normalize_fields
    self.email.downcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.most_recent
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # @posts = Post.limit(4)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def drafts
    @posts = Post.unpublished
    render :index
  end

  def search
    @results = Post.search(params[:q])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:subject, :body, :published_at)
  end
end

# any public method is an action, private are helpers
# These are controller actions

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to @user #goes to user - show.html.erb
    else
      render :new     #rails will look in views folder for new.html.erb
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def users_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StacyHwBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_local_field :published_at %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="header">
<h1 class="blogtitle">Stacy's Blog</h1>
</div>
<div class="container">
<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>Date/Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @posts.empty? %>
      <td class="noposts">No Posts available</td>
    <% else %>
    <% @posts.each do |post| %>
      <tr>

        <td class="subject"><%= post.subject %></td>
        <td class="body"><%= post.body %></td>
        <td class="published_at"><%= post.published_at %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td class="notice"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<div class="links">
<p class="button"><%= link_to 'New Post', new_post_path %></p>
<p class="button"><%= link_to 'Become a member of my clan!', users_path %></p>
<p class="button"><%= link_to 'Home', root_path %></p>
<%= form_tag(search_posts_path, method: "get") do %>
  <%= label_tag(:q, "Search for awesomness:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

</div>
</div>
<!-- <a href="https://www.google.com/">Search Google</a> -->

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<div class="container">
<h1>Stacy's Blog</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>Date/Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |post| %>
      <tr>

        <td><%= post.subject %></td>
        <td><%= post.body %></td>
        <td><%= post.published_at %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<%= form_tag(search_posts_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>
<a href="www.google.com">Search Google</a>
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @post.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<div class="header">
<h1 class="blogtitle">Stacy's Users</h1>
</div>

<div class="container">

<p class="button"><%= link_to 'Sign up', new_user_path %></p>
<p class="orelse">or else......</p>
<br>
<p class="button"><%= link_to 'Post Page', posts_path %></p>
<br>
<p class="button"><%= link_to 'Home', root_path %></p>

</div>
<br>

app/views/users/new.html.erb
<h1> Become my Minion! </h1>
<h3>(Creating a new user)</h3>
<% if @user.errors.any? %>
<b> Errors:</b>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %> </li>
    <% end %>
</ul>
<% end %> 

<%= form_for @user do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>

   <%= f.label :email %>
   <%= f.text_field :email %>

   <%= f.label :password %>
   <%= f.password_field :password %>

   <%= f.label :password_confirmation, 'Confirm Password' %>
   <%= f.password_field :password_confirmation %>

   <%= f.submit 'Submit', id: 'submit' %>
  <% end %>

app/views/users/show.html.erb
<h1> Welcome, you poor unfortunate soul! </h1>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p class="button"><%= link_to 'Post Page', posts_path %></p>
<p class="button"><%= link_to 'Back', users_path %></p>

app/views/welcome/home.html.erb
<div class="welcomepage" >
<h1 class="day">*High Five*</h1>
<h1 class="stacy"> Stacy's Blog </h1>

<div id="bloglink"> <%= link_to 'Click me, I\'m learning things', posts_path %> </div>
<div id="bloglink"><a href="https://www.linkedin.com/pub/stacy-banks/31/575/679">Or click me, I'm professional (Linkedin)</a></div>
</div>